server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vrs
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
