server:
  port: 8080



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vrs
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  aop:
    auto: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

    mvc:
      validation: true

    vrs:
      minio:
        url: http://localhost:9000
        accessKey: esewa
        secretKey: esewa@123#
        bucket: vrs-bucket
        secure: false
        expiry: 180
        imageSize: 20971520
        fileSize: 20971520


    default-user:
      firstName: super
      middleName:
      lastName: admin
      password: superadmin
      email: superadmin@gmail.com
      mobileNumber: 9843123495

  main:
    allow-bean-definition-overriding: true


mongodb:
  secondary:
    host: localhost
    port: 27017
    database: vrs
    username: root
    password: root
    authenticationDatabase: admin

logging:
  level:
    org.springframework.aop: DEBUG
